os:
- linux
language: go
go:
- tip
script:
- go get ./...
- go build
deploy:
  provider: releases
  api_key:
    secure: nsycToSisgfGXTIe/xqK6YXnLZNzJWkOfKkmPVQC7KdrlHFHhvv9FbzKJw6nQB38lnzlEDJXd1I+58MzlukMziu+uiHTmXtBQO8giRixYmxl6P+eV97hJiXorzLNB6vAVQICHHpiUSpEMfjfiCAMCzwrOMvt3Xect8o/Nd3hSA1dzZY52xbLZcQpUKLoVj8h8Lrrkum7TZUMH2NqJxesMqo8ktTHTIxCHuyNAJwjcAte1o9Mdv5lnAZmdc3STLnA6dxwpz2BfSftHxLoFpdJmvlDTLMcvcgRuL5JPTBk7coqDsu9HBxIK88Ql8rKs40/oX2Jcy0QMDlAPkUfmixT6ut+1sbJ73fRLSjDXBGZxegg087GcMHt6UKVDLoxBhE1dQ14F10qYiNypm3oYUfuGJPJLWazmoSJewX1ybS+K2/Utuvc9Z/4ikWYOSX40HdmdYrAsG6A71Ng2kEwj1sHVwg0PMQvDjebQmIlf7xHD2ECEk3KJ2rhZyqqyxfpYD0sR+ptp9j3Er93wW4bUKQHfHvN/3tajK5aAZmPzviKFl9NiQjeqwpy9GoV+bKo7FW/eBd02JLiWwIg5E/bClHhlG2cmLWPX1axmPvVUiSe2YH6G4HvVJSmJxkAp5LPaWJI/0l8oveNc3W+Io4pfm33au6neXqXgcFipZdmliR0+jE=
  file: ecs-manager
  on:
    repo: sd-charris/ecs-manager
    tags: true